USE [StatureDev]
GO

/****** Object:  View [dbo].[X_ACS QAs]    Script Date: 9/5/2025 2:43:18 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE   view [dbo].[X_ACS QAs]
AS

select [ROW_ID]
      ,[VERSION_ID]
      ,[REVISION_ID]
      ,[FULL_VERSION_NAME]
      ,[BO_TYPE_NAME]
      ,[BO_TYPE_VERSION_NUMBER]
      ,[U_Revision_Name]
      ,[R_Revision_Name]
      ,[U_Quality_Attribute_Category]
      ,[R_Quality_Attribute_Category]
      ,[U_Quality_Attribute]
      ,[R_Quality_Attribute]
      ,[U_Criticality_Assignment]
      ,[R_Criticality_Assignment]
      ,[U_Send_Non_CQA_to_Assay_RO___]
      ,[R_Send_Non_CQA_to_Assay_RO___]
      ,[U_Assay]
      ,[R_Assay]
      ,[U_Assay_Readout]
      ,[R_Assay_Readout]
      ,[C_Max_SPCRS_Per_QA] as [U_Max_SPCRS_Per_QA]
      ,[R_Max_SPCRS_Per_QA]
      ,[C_Final_Scaled_Process_Capabi] as [U_Final_Scaled_Process_Capabi]
      ,[R_Final_Scaled_Process_Capabi]
      ,[U_Justification]
      ,[R_Justification]
      ,[U_Phase_Supportable]
      ,[R_Phase_Supportable]
      ,[U_Sample_Type]
      ,[R_Sample_Type]
      ,[U_Testing_Supportable]
      ,[R_Testing_Supportable]
      ,[U_Limit]
      ,[R_Limit]
      ,[U_Location_of_Method]
      ,[R_Location_of_Method]
      ,[U_Reference]
      ,[R_Reference]
      ,[C_CQA_Severity_Score] as [U_CQA_Severity_Score]
      ,[R_CQA_Severity_Score]
      ,[U_Analytical_Detection_Score]
      ,[R_Analytical_Detection_Score]
      ,[C_Risk_to_Patient_Score] as [U_Risk_to_Patient_Score]
      ,[R_Risk_to_Patient_Score]
      ,[U_Scaled_Risk_to_Patient_Score]
      ,[R_Scaled_Risk_to_Patient_Score]
      ,[U_Applicability]
      ,[R_Applicability] from [StatureDev].[dbo].[X_ACS - QAs Global_rel_new] where "C_Criticality_Assignment"='CQA' OR "C_Send_Non_CQA_to_Assay_RO___"='Y' 
union 
select [ROW_ID]
      ,[VERSION_ID]
      ,[REVISION_ID]
      ,[FULL_VERSION_NAME]
      ,[BO_TYPE_NAME]
      ,[BO_TYPE_VERSION_NUMBER]
      ,[U_Revision_Name]
      ,[R_Revision_Name]
      ,[U_Quality_Attribute_Category]
      ,[R_Quality_Attribute_Category]
      ,[U_Quality_Attribute]
      ,[R_Quality_Attribute]
      ,[U_Criticality_Assignment]
      ,[R_Criticality_Assignment]
      ,[U_Send_Non_CQA_to_Assay_RO___]
      ,[R_Send_Non_CQA_to_Assay_RO___]
      ,[U_Assay]
      ,[R_Assay]
      ,[U_Assay_Readout]
      ,[R_Assay_Readout]
      ,[C_Max_SPCRS_Per_QA] as [U_Max_SPCRS_Per_QA]
      ,[R_Max_SPCRS_Per_QA]
      ,[C_Final_Scaled_Process_Capabi] as [U_Final_Scaled_Process_Capabi]
      ,[R_Final_Scaled_Process_Capabi]
      ,[U_Justification]
      ,[R_Justification]
      ,[U_Phase_Supportable]
      ,[R_Phase_Supportable]
      ,[U_Sample_Type]
      ,[R_Sample_Type]
      ,[U_Testing_Supportable]
      ,[R_Testing_Supportable]
      ,[U_Limit]
      ,[R_Limit]
      ,[U_Location_of_Method]
      ,[R_Location_of_Method]
      ,[U_Reference]
      ,[R_Reference]
      ,[C_CQA_Severity_Score] as [U_CQA_Severity_Score]
      ,[R_CQA_Severity_Score]
      ,[U_Analytical_Detection_Score]
      ,[R_Analytical_Detection_Score]
      ,[C_Risk_to_Patient_Score] as [U_Risk_to_Patient_Score]
      ,[R_Risk_to_Patient_Score]
      ,[U_Scaled_Risk_to_Patient_Score]
      ,[R_Scaled_Risk_to_Patient_Score]
      ,[U_Applicability]
      ,[R_Applicability] from [StatureDev].[dbo].[X_ACS - QAs Site_publish_new] where "C_Criticality_Assignment"='CQA' OR "C_Send_Non_CQA_to_Assay_RO___"='Y'
union
select [ROW_ID]
      ,[VERSION_ID]
      ,[REVISION_ID]
      ,[FULL_VERSION_NAME]
      ,[BO_TYPE_NAME]
      ,[BO_TYPE_VERSION_NUMBER]
      ,[U_Revision_Name]
      ,[R_Revision_Name]
      ,[U_Quality_Attribute_Category]
      ,[R_Quality_Attribute_Category]
      ,[U_Quality_Attribute]
      ,[R_Quality_Attribute]
      ,[U_Criticality_Assignment]
      ,[R_Criticality_Assignment]
      ,[U_Send_Non_CQA_to_Assay_RO___]
      ,[R_Send_Non_CQA_to_Assay_RO___]
      ,[U_Assay]
      ,[R_Assay]
      ,[U_Assay_Readout]
      ,[R_Assay_Readout]
      ,[C_Max_SPCRS_Per_QA] as [U_Max_SPCRS_Per_QA]
      ,[R_Max_SPCRS_Per_QA]
      ,[C_Final_Scaled_Process_Capabi] as [U_Final_Scaled_Process_Capabi]
      ,[R_Final_Scaled_Process_Capabi]
      ,[U_Justification]
      ,[R_Justification]
      ,[U_Phase_Supportable]
      ,[R_Phase_Supportable]
      ,[U_Sample_Type]
      ,[R_Sample_Type]
      ,[U_Testing_Supportable]
      ,[R_Testing_Supportable]
      ,[U_Limit]
      ,[R_Limit]
      ,[U_Location_of_Method]
      ,[R_Location_of_Method]
      ,[U_Reference]
      ,[R_Reference]
      ,[C_CQA_Severity_Score] as [U_CQA_Severity_Score]
      ,[R_CQA_Severity_Score]
      ,[U_Analytical_Detection_Score]
      ,[R_Analytical_Detection_Score]
      ,[C_Risk_to_Patient_Score] as [U_Risk_to_Patient_Score]
      ,[R_Risk_to_Patient_Score]
      ,[U_Scaled_Risk_to_Patient_Score]
      ,[R_Scaled_Risk_to_Patient_Score]
      ,[U_Applicability]
      ,[R_Applicability] from [StatureDev].[dbo].[X_ACS - QAs Global_pub_new] where "C_Criticality_Assignment"='CQA' OR "C_Send_Non_CQA_to_Assay_RO___"='Y'
union
select [ROW_ID]
      ,[VERSION_ID]
      ,[REVISION_ID]
      ,[FULL_VERSION_NAME]
      ,[BO_TYPE_NAME]
      ,[BO_TYPE_VERSION_NUMBER]
      ,[U_Revision_Name]
      ,[R_Revision_Name]
      ,[U_Quality_Attribute_Category]
      ,[R_Quality_Attribute_Category]
      ,[U_Quality_Attribute]
      ,[R_Quality_Attribute]
      ,[U_Criticality_Assignment]
      ,[R_Criticality_Assignment]
      ,[U_Send_Non_CQA_to_Assay_RO___]
      ,[R_Send_Non_CQA_to_Assay_RO___]
      ,[U_Assay]
      ,[R_Assay]
      ,[U_Assay_Readout]
      ,[R_Assay_Readout]
      ,[C_Max_SPCRS_Per_QA] as [U_Max_SPCRS_Per_QA]
      ,[R_Max_SPCRS_Per_QA]
      ,[C_Final_Scaled_Process_Capabi] as [U_Final_Scaled_Process_Capabi]
      ,[R_Final_Scaled_Process_Capabi]
      ,[U_Justification]
      ,[R_Justification]
      ,[U_Phase_Supportable]
      ,[R_Phase_Supportable]
      ,[U_Sample_Type]
      ,[R_Sample_Type]
      ,[U_Testing_Supportable]
      ,[R_Testing_Supportable]
      ,[U_Limit]
      ,[R_Limit]
      ,[U_Location_of_Method]
      ,[R_Location_of_Method]
      ,[U_Reference]
      ,[R_Reference]
      ,[C_CQA_Severity_Score] as [U_CQA_Severity_Score]
      ,[R_CQA_Severity_Score]
      ,[U_Analytical_Detection_Score]
      ,[R_Analytical_Detection_Score]
      ,[C_Risk_to_Patient_Score] as [U_Risk_to_Patient_Score]
      ,[R_Risk_to_Patient_Score]
      ,[U_Scaled_Risk_to_Patient_Score]
      ,[R_Scaled_Risk_to_Patient_Score]
      ,[U_Applicability]
      ,[R_Applicability] from [StatureDev].[dbo].[X_ACS - QAs Site_draft_new] where "C_Criticality_Assignment"='CQA' OR "C_Send_Non_CQA_to_Assay_RO___"='Y'


GO


