USE [StatureDev]
GO

/****** Object:  View [dbo].[X_PCA Full View]    Script Date: 9/5/2025 2:56:03 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO









CREATE   view [dbo].[X_PCA Full View]
AS 
SELECT [ROW_ID]
      ,[VERSION_ID]
      ,[REVISION_ID]
      ,[FULL_VERSION_NAME]
      ,[BO_TYPE_NAME]
      ,[BO_TYPE_VERSION_NUMBER]
      ,[U_Revision_Name]
      ,[R_Revision_Name]
      ,[U_Process_Segment]
      ,[R_Process_Segment]
      ,[U_Unit_Operation]
      ,[R_Unit_Operation]
      ,[U_Sub_Step]
      ,[R_Sub_Step]
      ,[U_Parameter___Material]
      ,[R_Parameter___Material]
      ,[U_Parameter_Type]
      ,[R_Parameter_Type]
      ,[U_Unit_of_Measure]
      ,[R_Unit_of_Measure]
      ,[U_Range]
      ,[R_Range]
      ,[C_Set_Point] as [U_Set_Point]
      ,[R_Set_Point]
      ,[C_NOR_LL] as [U_NOR_LL]
      ,[R_NOR_LL]
      ,[C_NOR_UL] as [U_NOR_UL]
      ,[R_NOR_UL]
      ,[U_Assessment_Range]
      ,[R_Assessment_Range]
      ,[U_Justification_for_Assessmen]
      ,[R_Justification_for_Assessmen]
      ,[U_Applicability]
      ,[R_Applicability]
      ,[U_Interaction_with_Other_Para]
      ,[R_Interaction_with_Other_Para]
      ,[U_QA]
      ,[R_QA]
      ,[C_QA_PCA_Score] as [U_QA_PCA_Score]
      ,[R_QA_PCA_Score]
      ,[C_Max_QA_PCA_Score] as [U_Max_QA_PCA_Score]
      ,[R_Max_QA_PCA_Score]
      ,[U_PPI]
      ,[R_PPI]
      ,[C_PPI_PCA_Score] as [U_PPI_PCA_Score]
      ,[R_PPI_PCA_Score]
      ,[C_Max_PPI_PCA_Score] as [U_Max_PPI_PCA_Score]
      ,[R_Max_PPI_PCA_Score]
      ,[C_Max_PCA_Score] as [U_Max_PCA_Score]
      ,[R_Max_PCA_Score]
      ,[U_Keyword]
      ,[R_Keyword]
      ,[U_Justification_Description]
      ,[R_Justification_Description]
      ,[U_References]
      ,[R_References]
      ,[U_Recommended_Study_Type]
      ,[R_Recommended_Study_Type]
      ,[U_Comments_for_Study_Type]
      ,[R_Comments_for_Study_Type]
      ,[U_Send_To_PrCA]
      ,[R_Send_To_PrCA] FROM [StatureDev].[dbo].[X_PCA FULL Global_publish_new]
union
SELECT [ROW_ID]
      ,[VERSION_ID]
      ,[REVISION_ID]
      ,[FULL_VERSION_NAME]
      ,[BO_TYPE_NAME]
      ,[BO_TYPE_VERSION_NUMBER]
      ,[U_Revision_Name]
      ,[R_Revision_Name]
      ,[U_Process_Segment]
      ,[R_Process_Segment]
      ,[U_Unit_Operation]
      ,[R_Unit_Operation]
      ,[U_Sub_Step]
      ,[R_Sub_Step]
      ,[U_Parameter___Material]
      ,[R_Parameter___Material]
      ,[U_Parameter_Type]
      ,[R_Parameter_Type]
      ,[U_Unit_of_Measure]
      ,[R_Unit_of_Measure]
      ,[U_Range]
      ,[R_Range]
      ,[C_Set_Point] as [U_Set_Point]
      ,[R_Set_Point]
      ,[C_NOR_LL] as [U_NOR_LL]
      ,[R_NOR_LL]
      ,[C_NOR_UL] as [U_NOR_UL]
      ,[R_NOR_UL]
      ,[U_Assessment_Range]
      ,[R_Assessment_Range]
      ,[U_Justification_for_Assessmen]
      ,[R_Justification_for_Assessmen]
      ,[U_Applicability]
      ,[R_Applicability]
      ,[U_Interaction_with_Other_Para]
      ,[R_Interaction_with_Other_Para]
      ,[U_QA]
      ,[R_QA]
      ,[C_QA_PCA_Score] as [U_QA_PCA_Score]
      ,[R_QA_PCA_Score]
      ,[C_Max_QA_PCA_Score] as [U_Max_QA_PCA_Score]
      ,[R_Max_QA_PCA_Score]
      ,[U_PPI]
      ,[R_PPI]
      ,[C_PPI_PCA_Score] as [U_PPI_PCA_Score]
      ,[R_PPI_PCA_Score]
      ,[C_Max_PPI_PCA_Score] as [U_Max_PPI_PCA_Score]
      ,[R_Max_PPI_PCA_Score]
      ,[C_Max_PCA_Score] as [U_Max_PCA_Score]
      ,[R_Max_PCA_Score]
      ,[U_Keyword]
      ,[R_Keyword]
      ,[U_Justification_Description]
      ,[R_Justification_Description]
      ,[U_References]
      ,[R_References]
      ,[U_Recommended_Study_Type]
      ,[R_Recommended_Study_Type]
      ,[U_Comments_for_Study_Type]
      ,[R_Comments_for_Study_Type]
      ,[U_Send_To_PrCA]
      ,[R_Send_To_PrCA] FROM [StatureDev].[dbo].[X_PCA FULL Global_released_new]
union
SELECT [ROW_ID]
      ,[VERSION_ID]
      ,[REVISION_ID]
      ,[FULL_VERSION_NAME]
      ,[BO_TYPE_NAME]
      ,[BO_TYPE_VERSION_NUMBER]
      ,[U_Revision_Name]
      ,[R_Revision_Name]
      ,[U_Process_Segment]
      ,[R_Process_Segment]
      ,[U_Unit_Operation]
      ,[R_Unit_Operation]
      ,[U_Sub_Step]
      ,[R_Sub_Step]
      ,[U_Parameter___Material]
      ,[R_Parameter___Material]
      ,[U_Parameter_Type]
      ,[R_Parameter_Type]
      ,[U_Unit_of_Measure]
      ,[R_Unit_of_Measure]
      ,[U_Range]
      ,[R_Range]
      ,[C_Set_Point] as [U_Set_Point]
      ,[R_Set_Point]
      ,[C_NOR_LL] as [U_NOR_LL]
      ,[R_NOR_LL]
      ,[C_NOR_UL] as [U_NOR_UL]
      ,[R_NOR_UL]
      ,[U_Assessment_Range]
      ,[R_Assessment_Range]
      ,[U_Justification_for_Assessmen]
      ,[R_Justification_for_Assessmen]
      ,[U_Applicability]
      ,[R_Applicability]
      ,[U_Interaction_with_Other_Para]
      ,[R_Interaction_with_Other_Para]
      ,[U_QA]
      ,[R_QA]
      ,[C_QA_PCA_Score] as [U_QA_PCA_Score]
      ,[R_QA_PCA_Score]
      ,[C_Max_QA_PCA_Score] as [U_Max_QA_PCA_Score]
      ,[R_Max_QA_PCA_Score]
      ,[U_PPI]
      ,[R_PPI]
      ,[C_PPI_PCA_Score] as [U_PPI_PCA_Score]
      ,[R_PPI_PCA_Score]
      ,[C_Max_PPI_PCA_Score] as [U_Max_PPI_PCA_Score]
      ,[R_Max_PPI_PCA_Score]
      ,[C_Max_PCA_Score] as [U_Max_PCA_Score]
      ,[R_Max_PCA_Score]
      ,[U_Keyword]
      ,[R_Keyword]
      ,[U_Justification_Description]
      ,[R_Justification_Description]
      ,[U_References]
      ,[R_References]
      ,[U_Recommended_Study_Type]
      ,[R_Recommended_Study_Type]
      ,[U_Comments_for_Study_Type]
      ,[R_Comments_for_Study_Type]
      ,[U_Send_To_PrCA]
      ,[R_Send_To_PrCA] FROM [StatureDev].[dbo].[X_PCA Full View_Site_pub_new] where U_Unit_Operation is not null
union
SELECT [ROW_ID]
      ,[VERSION_ID]
      ,[REVISION_ID]
      ,[FULL_VERSION_NAME]
      ,[BO_TYPE_NAME]
      ,[BO_TYPE_VERSION_NUMBER]
      ,[U_Revision_Name]
      ,[R_Revision_Name]
      ,[U_Process_Segment]
      ,[R_Process_Segment]
      ,[U_Unit_Operation]
      ,[R_Unit_Operation]
      ,[U_Sub_Step]
      ,[R_Sub_Step]
      ,[U_Parameter___Material]
      ,[R_Parameter___Material]
      ,[U_Parameter_Type]
      ,[R_Parameter_Type]
      ,[U_Unit_of_Measure]
      ,[R_Unit_of_Measure]
      ,[U_Range]
      ,[R_Range]
      ,[C_Set_Point] as [U_Set_Point]
      ,[R_Set_Point]
      ,[C_NOR_LL] as [U_NOR_LL]
      ,[R_NOR_LL]
      ,[C_NOR_UL] as [U_NOR_UL]
      ,[R_NOR_UL]
      ,[U_Assessment_Range]
      ,[R_Assessment_Range]
      ,[U_Justification_for_Assessmen]
      ,[R_Justification_for_Assessmen]
      ,[U_Applicability]
      ,[R_Applicability]
      ,[U_Interaction_with_Other_Para]
      ,[R_Interaction_with_Other_Para]
      ,[U_QA]
      ,[R_QA]
      ,[C_QA_PCA_Score] as [U_QA_PCA_Score]
      ,[R_QA_PCA_Score]
      ,[C_Max_QA_PCA_Score] as [U_Max_QA_PCA_Score]
      ,[R_Max_QA_PCA_Score]
      ,[U_PPI]
      ,[R_PPI]
      ,[C_PPI_PCA_Score] as [U_PPI_PCA_Score]
      ,[R_PPI_PCA_Score]
      ,[C_Max_PPI_PCA_Score] as [U_Max_PPI_PCA_Score]
      ,[R_Max_PPI_PCA_Score]
      ,[C_Max_PCA_Score] as [U_Max_PCA_Score]
      ,[R_Max_PCA_Score]
      ,[U_Keyword]
      ,[R_Keyword]
      ,[U_Justification_Description]
      ,[R_Justification_Description]
      ,[U_References]
      ,[R_References]
      ,[U_Recommended_Study_Type]
      ,[R_Recommended_Study_Type]
      ,[U_Comments_for_Study_Type]
      ,[R_Comments_for_Study_Type]
      ,[U_Send_To_PrCA]
      ,[R_Send_To_PrCA] FROM [StatureDev].[dbo].[X_PCA FULL View_Site_draft] where U_Unit_Operation is not null
GO


