USE [StatureDev]
GO

/****** Object:  View [dbo].[X_Process Description QA PPI]    Script Date: 9/5/2025 2:46:58 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO









CREATE view [dbo].[X_Process Description QA PPI]
AS
SELECT [ROW_ID]
      ,[VERSION_ID]
      ,[REVISION_ID]
      ,[FULL_VERSION_NAME]
      ,[BO_TYPE_NAME]
      ,[BO_TYPE_VERSION_NUMBER]
      ,[U_Revision_Name]
      ,[R_Revision_Name]
      ,[U_Process_Segment]
      ,[R_Process_Segment]
      ,[U_RowNumber001]
      ,[R_RowNumber001]
      ,[U_Unit_Operation]
      ,[R_Unit_Operation]
      ,[U_RowNumber002]
      ,[R_RowNumber002]
      ,[U_Purpose_of_Unit_Operation]
      ,[R_Purpose_of_Unit_Operation]
      ,[U_Sub_Step]
      ,[R_Sub_Step]
      ,[U_RowNumber003]
      ,[R_RowNumber003]
      ,[U_Parameter___Equipment___Mat]
      ,[R_Parameter___Equipment___Mat]
      ,[U_RowNumber004]
      ,[R_RowNumber004]
      ,[U_Parameter_Type]
      ,[R_Parameter_Type]
      ,[U_Unit_of_Measure]
      ,[R_Unit_of_Measure]
      ,[U_Normal_Operating_Range]
      ,[R_Normal_Operating_Range]
      ,[C_Set_Point] as [U_Set_Point]
      ,[R_Set_Point]
      ,[C_NOR_LL] as [U_NOR_LL]
      ,[R_NOR_LL]
      ,[C_NOR_UL] as [U_NOR_UL]
      ,[R_NOR_UL]
      ,[C_Criticality_Designation]
      ,[U_Criticality_Designation]
      ,[R_Criticality_Designation]
      ,[C_Proven_Acceptable_Range__PA]
      ,[U_Proven_Acceptable_Range__PA]
      ,[R_Proven_Acceptable_Range__PA]
      ,[C_QA_PPI]
      ,[U_QA_PPI]
      ,[R_QA_PPI]
      ,[C_Score] as [U_Score]
      ,[R_Score]
      ,[C_Max_PCA_Score]
      ,[U_Max_PCA_Score]
      ,[R_Max_PCA_Score]
      ,[C_Keyword]
      ,[U_Keyword]
      ,[R_Keyword]
      ,[C_Justification_Description]
      ,[U_Justification_Description]
      ,[R_Justification_Description]
      ,[C_Max_Impact_Score__PrCA_] as [U_Max_Impact_Score__PrCA_]
      ,[R_Max_Impact_Score__PrCA_]
      ,[C_Max_Severity_Score__FMEA_PF] as [U_Max_Severity_Score__FMEA_PF]
      ,[R_Max_Severity_Score__FMEA_PF]
      ,[C_PCRS_RPN]
      ,[U_PCRS_RPN]
      ,[R_PCRS_RPN]
      ,[C_Conf_]
      ,[U_Conf_]
      ,[R_Conf_]
      ,[C_Applicability]
      ,[U_Applicability]
      ,[R_Applicability] FROM [StatureDev].[dbo].[X_ProcDescQAPPIGlbl_pub_new] where C_Parameter_Type in ('PP','EC','MC','RM','MA','IA')
union 
SELECT [ROW_ID]
      ,[VERSION_ID]
      ,[REVISION_ID]
      ,[FULL_VERSION_NAME]
      ,[BO_TYPE_NAME]
      ,[BO_TYPE_VERSION_NUMBER]
      ,[U_Revision_Name]
      ,[R_Revision_Name]
      ,[U_Process_Segment]
      ,[R_Process_Segment]
      ,[U_RowNumber001]
      ,[R_RowNumber001]
      ,[U_Unit_Operation]
      ,[R_Unit_Operation]
      ,[U_RowNumber002]
      ,[R_RowNumber002]
      ,[U_Purpose_of_Unit_Operation]
      ,[R_Purpose_of_Unit_Operation]
      ,[U_Sub_Step]
      ,[R_Sub_Step]
      ,[U_RowNumber003]
      ,[R_RowNumber003]
      ,[U_Parameter___Equipment___Mat]
      ,[R_Parameter___Equipment___Mat]
      ,[U_RowNumber004]
      ,[R_RowNumber004]
      ,[U_Parameter_Type]
      ,[R_Parameter_Type]
      ,[U_Unit_of_Measure]
      ,[R_Unit_of_Measure]
      ,[U_Normal_Operating_Range]
      ,[R_Normal_Operating_Range]
      ,[C_Set_Point] as [U_Set_Point]
      ,[R_Set_Point]
      ,[C_NOR_LL] as [U_NOR_LL]
      ,[R_NOR_LL]
      ,[C_NOR_UL] as [U_NOR_UL]
      ,[R_NOR_UL]
      ,[C_Criticality_Designation]
      ,[U_Criticality_Designation]
      ,[R_Criticality_Designation]
      ,[C_Proven_Acceptable_Range__PA]
      ,[U_Proven_Acceptable_Range__PA]
      ,[R_Proven_Acceptable_Range__PA]
      ,[C_QA_PPI]
      ,[U_QA_PPI]
      ,[R_QA_PPI]
      ,[C_Score] as [U_Score]
      ,[R_Score]
      ,[C_Max_PCA_Score]
      ,[U_Max_PCA_Score]
      ,[R_Max_PCA_Score]
      ,[C_Keyword]
      ,[U_Keyword]
      ,[R_Keyword]
      ,[C_Justification_Description]
      ,[U_Justification_Description]
      ,[R_Justification_Description]
      ,[C_Max_Impact_Score__PrCA_] as [U_Max_Impact_Score__PrCA_]
      ,[R_Max_Impact_Score__PrCA_]
      ,[C_Max_Severity_Score__FMEA_PF] as [U_Max_Severity_Score__FMEA_PF]
      ,[R_Max_Severity_Score__FMEA_PF]
      ,[C_PCRS_RPN]
      ,[U_PCRS_RPN]
      ,[R_PCRS_RPN]
      ,[C_Conf_]
      ,[U_Conf_]
      ,[R_Conf_]
      ,[C_Applicability]
      ,[U_Applicability]
      ,[R_Applicability] FROM [StatureDev].[dbo].[X_ProcDescQAPPIGlbl_rel_new] where C_Parameter_Type in ('PP','EC','MC','RM','MA','IA')
union 
SELECT [ROW_ID]
      ,[VERSION_ID]
      ,[REVISION_ID]
      ,[FULL_VERSION_NAME]
      ,[BO_TYPE_NAME]
      ,[BO_TYPE_VERSION_NUMBER]
      ,[U_Revision_Name]
      ,[R_Revision_Name]
      ,[U_Process_Segment]
      ,[R_Process_Segment]
      ,[U_RowNumber001]
      ,[R_RowNumber001]
      ,[U_Unit_Operation]
      ,[R_Unit_Operation]
      ,[U_RowNumber002]
      ,[R_RowNumber002]
      ,[U_Purpose_of_Unit_Operation]
      ,[R_Purpose_of_Unit_Operation]
      ,[U_Sub_Step]
      ,[R_Sub_Step]
      ,[U_RowNumber003]
      ,[R_RowNumber003]
      ,[U_Parameter___Equipment___Mat]
      ,[R_Parameter___Equipment___Mat]
      ,[U_RowNumber004]
      ,[R_RowNumber004]
      ,[U_Parameter_Type]
      ,[R_Parameter_Type]
      ,[U_Unit_of_Measure]
      ,[R_Unit_of_Measure]
      ,[U_Normal_Operating_Range]
      ,[R_Normal_Operating_Range]
      ,[C_Set_Point] as [U_Set_Point]
      ,[R_Set_Point]
      ,[C_NOR_LL] as [U_NOR_LL]
      ,[R_NOR_LL]
      ,[C_NOR_UL] as [U_NOR_UL]
      ,[R_NOR_UL]
      ,[C_Criticality_Designation]
      ,[U_Criticality_Designation]
      ,[R_Criticality_Designation]
      ,[C_Proven_Acceptable_Range__PA]
      ,[U_Proven_Acceptable_Range__PA]
      ,[R_Proven_Acceptable_Range__PA]
      ,[C_QA_PPI]
      ,[U_QA_PPI]
      ,[R_QA_PPI]
      ,[C_Score] as [U_Score]
      ,[R_Score]
      ,[C_Max_PCA_Score]
      ,[U_Max_PCA_Score]
      ,[R_Max_PCA_Score]
      ,[C_Keyword]
      ,[U_Keyword]
      ,[R_Keyword]
      ,[C_Justification_Description]
      ,[U_Justification_Description]
      ,[R_Justification_Description]
      ,[C_Max_Impact_Score__PrCA_] as [U_Max_Impact_Score__PrCA_]
      ,[R_Max_Impact_Score__PrCA_]
      ,[C_Max_Severity_Score__FMEA_PF] as [U_Max_Severity_Score__FMEA_PF]
      ,[R_Max_Severity_Score__FMEA_PF]
      ,[C_PCRS_RPN]
      ,[U_PCRS_RPN]
      ,[R_PCRS_RPN]
      ,[C_Conf_]
      ,[U_Conf_]
      ,[R_Conf_]
      ,[C_Applicability]
      ,[U_Applicability]
      ,[R_Applicability] FROM [StatureDev].[dbo].[X_Pro Des QA PPI Site_pub_new] where C_Parameter_Type in ('PP','EC','MC','RM','MA','IA')
union 
SELECT [ROW_ID]
      ,[VERSION_ID]
      ,[REVISION_ID]
      ,[FULL_VERSION_NAME]
      ,[BO_TYPE_NAME]
      ,[BO_TYPE_VERSION_NUMBER]
      ,[U_Revision_Name]
      ,[R_Revision_Name]
      ,[U_Process_Segment]
      ,[R_Process_Segment]
      ,[U_RowNumber001]
      ,[R_RowNumber001]
      ,[U_Unit_Operation]
      ,[R_Unit_Operation]
      ,[U_RowNumber002]
      ,[R_RowNumber002]
      ,[U_Purpose_of_Unit_Operation]
      ,[R_Purpose_of_Unit_Operation]
      ,[U_Sub_Step]
      ,[R_Sub_Step]
      ,[U_RowNumber003]
      ,[R_RowNumber003]
      ,[U_Parameter___Equipment___Mat]
      ,[R_Parameter___Equipment___Mat]
      ,[U_RowNumber004]
      ,[R_RowNumber004]
      ,[U_Parameter_Type]
      ,[R_Parameter_Type]
      ,[U_Unit_of_Measure]
      ,[R_Unit_of_Measure]
      ,[U_Normal_Operating_Range]
      ,[R_Normal_Operating_Range]
      ,[C_Set_Point] as [U_Set_Point]
      ,[R_Set_Point]
      ,[C_NOR_LL] as [U_NOR_LL]
      ,[R_NOR_LL]
      ,[C_NOR_UL] as [U_NOR_UL]
      ,[R_NOR_UL]
      ,[C_Criticality_Designation]
      ,[U_Criticality_Designation]
      ,[R_Criticality_Designation]
      ,[C_Proven_Acceptable_Range__PA]
      ,[U_Proven_Acceptable_Range__PA]
      ,[R_Proven_Acceptable_Range__PA]
      ,[C_QA_PPI]
      ,[U_QA_PPI]
      ,[R_QA_PPI]
      ,[C_Score] as [U_Score]
      ,[R_Score]
      ,[C_Max_PCA_Score]
      ,[U_Max_PCA_Score]
      ,[R_Max_PCA_Score]
      ,[C_Keyword]
      ,[U_Keyword]
      ,[R_Keyword]
      ,[C_Justification_Description]
      ,[U_Justification_Description]
      ,[R_Justification_Description]
      ,[C_Max_Impact_Score__PrCA_] as [U_Max_Impact_Score__PrCA_]
      ,[R_Max_Impact_Score__PrCA_]
      ,[C_Max_Severity_Score__FMEA_PF] as [U_Max_Severity_Score__FMEA_PF]
      ,[R_Max_Severity_Score__FMEA_PF]
      ,[C_PCRS_RPN]
      ,[U_PCRS_RPN]
      ,[R_PCRS_RPN]
      ,[C_Conf_]
      ,[U_Conf_]
      ,[R_Conf_]
      ,[C_Applicability]
      ,[U_Applicability]
      ,[R_Applicability] FROM [StatureDev].[dbo].[X_Pro Des QA PPI Site_dft_new] where C_Parameter_Type in ('PP','EC','MC','RM','MA','IA')
GO


