USE [StatureDev]
GO

/****** Object:  View [dbo].[X_Process Attributes PPI Sel]    Script Date: 9/5/2025 2:46:28 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO









CREATE   view [dbo].[X_Process Attributes PPI Sel]
AS 
SELECT [ROW_ID]
      ,[VERSION_ID]
      ,[REVISION_ID]
      ,[FULL_VERSION_NAME]
      ,[BO_TYPE_NAME]
      ,[BO_TYPE_VERSION_NUMBER]
      ,[U_Revision_Name]
      ,[R_Revision_Name]
      ,[U_Process_Segment]
      ,[R_Process_Segment]
      ,[U_RowNumber001]
      ,[R_RowNumber001]
      ,[U_Unit_Operation]
      ,[R_Unit_Operation]
      ,[U_RowNumber002]
      ,[R_RowNumber002]
      ,[U_Sub_Step]
      ,[R_Sub_Step]
      ,[U_RowNumber003]
      ,[R_RowNumber003]
      ,[U_Process_Attribute]
      ,[R_Process_Attribute]
      ,[U_RowNumber004]
      ,[R_RowNumber004]
      ,[U_Attribute_Type]
      ,[R_Attribute_Type]
      ,[U_PPI_]
      ,[R_PPI_]
      ,[U_Test_Type]
      ,[R_Test_Type]
      ,[U_Limit_Type]
      ,[R_Limit_Type]
      ,[U_Limits]
      ,[R_Limits]
      ,[U_Site_Limits]
      ,[R_Site_Limits]
      ,[U_Applicability]
      ,[R_Applicability] FROM [StatureDev].[dbo].[X_ProcAttrPPISelGlbl_pub_new]

union
SELECT [ROW_ID]
      ,[VERSION_ID]
      ,[REVISION_ID]
      ,[FULL_VERSION_NAME]
      ,[BO_TYPE_NAME]
      ,[BO_TYPE_VERSION_NUMBER]
      ,[U_Revision_Name]
      ,[R_Revision_Name]
      ,[U_Process_Segment]
      ,[R_Process_Segment]
      ,[U_RowNumber001]
      ,[R_RowNumber001]
      ,[U_Unit_Operation]
      ,[R_Unit_Operation]
      ,[U_RowNumber002]
      ,[R_RowNumber002]
      ,[U_Sub_Step]
      ,[R_Sub_Step]
      ,[U_RowNumber003]
      ,[R_RowNumber003]
      ,[U_Process_Attribute]
      ,[R_Process_Attribute]
      ,[U_RowNumber004]
      ,[R_RowNumber004]
      ,[U_Attribute_Type]
      ,[R_Attribute_Type]
      ,[U_PPI_]
      ,[R_PPI_]
      ,[U_Test_Type]
      ,[R_Test_Type]
      ,[U_Limit_Type]
      ,[R_Limit_Type]
      ,[U_Limits]
      ,[R_Limits]
      ,[U_Site_Limits]
      ,[R_Site_Limits]
      ,[U_Applicability]
      ,[R_Applicability] FROM [StatureDev].[dbo].[X_ProcAttrPPISelGlbl_pub_new]
union
SELECT [ROW_ID]
      ,[VERSION_ID]
      ,[REVISION_ID]
      ,[FULL_VERSION_NAME]
      ,[BO_TYPE_NAME]
      ,[BO_TYPE_VERSION_NUMBER]
      ,[U_Revision_Name]
      ,[R_Revision_Name]
      ,[U_Process_Segment]
      ,[R_Process_Segment]
      ,[U_RowNumber001]
      ,[R_RowNumber001]
      ,[U_Unit_Operation]
      ,[R_Unit_Operation]
      ,[U_RowNumber002]
      ,[R_RowNumber002]
      ,[U_Sub_Step]
      ,[R_Sub_Step]
      ,[U_RowNumber003]
      ,[R_RowNumber003]
      ,[U_Process_Attribute]
      ,[R_Process_Attribute]
      ,[U_RowNumber004]
      ,[R_RowNumber004]
      ,[U_Attribute_Type]
      ,[R_Attribute_Type]
      ,[U_PPI_]
      ,[R_PPI_]
      ,[U_Test_Type]
      ,[R_Test_Type]
      ,[U_Limit_Type]
      ,[R_Limit_Type]
      ,[U_Limits]
      ,[R_Limits]
      ,[U_Site_Limits]
      ,[R_Site_Limits]
      ,[U_Applicability]
      ,[R_Applicability] FROM [StatureDev].[dbo].[X_ProAttrPPISelSite_pub_new] 
union
SELECT [ROW_ID]
      ,[VERSION_ID]
      ,[REVISION_ID]
      ,[FULL_VERSION_NAME]
      ,[BO_TYPE_NAME]
      ,[BO_TYPE_VERSION_NUMBER]
      ,[U_Revision_Name]
      ,[R_Revision_Name]
      ,[U_Process_Segment]
      ,[R_Process_Segment]
      ,[U_RowNumber001]
      ,[R_RowNumber001]
      ,[U_Unit_Operation]
      ,[R_Unit_Operation]
      ,[U_RowNumber002]
      ,[R_RowNumber002]
      ,[U_Sub_Step]
      ,[R_Sub_Step]
      ,[U_RowNumber003]
      ,[R_RowNumber003]
      ,[U_Process_Attribute]
      ,[R_Process_Attribute]
      ,[U_RowNumber004]
      ,[R_RowNumber004]
      ,[U_Attribute_Type]
      ,[R_Attribute_Type]
      ,[U_PPI_]
      ,[R_PPI_]
      ,[U_Test_Type]
      ,[R_Test_Type]
      ,[U_Limit_Type]
      ,[R_Limit_Type]
      ,[U_Limits]
      ,[R_Limits]
      ,[U_Site_Limits]
      ,[R_Site_Limits]
      ,[U_Applicability]
      ,[R_Applicability] FROM [StatureDev].[dbo].[X_ProAttrPPISelSite_rel_new] 
GO


