USE [StatureDev]
GO

/****** Object:  View [dbo].[X_PTP-Raw Material]    Script Date: 9/5/2025 2:49:09 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO








CREATE   view [dbo].[X_PTP-Raw Material]
AS 
SELECT [ROW_ID]
      ,[VERSION_ID]
      ,[REVISION_ID]
      ,[FULL_VERSION_NAME]
      ,[BO_TYPE_NAME]
      ,[BO_TYPE_VERSION_NUMBER]
      ,[U_Revision_Name]
      ,[R_Revision_Name]
      ,[U_Raw_Material]
      ,[R_Raw_Material]
      ,[U_An_Excipient_]
      ,[R_An_Excipient_]
      ,[U_Criticality_Designation_if_]
      ,[R_Criticality_Designation_if_]
      ,[U_SAP_JDE__Part_Number001]
      ,[R_SAP_JDE__Part_Number001]
      ,[U_Supplier_Name_Part_Number001]
      ,[R_Supplier_Name_Part_Number001]
      ,[U_Unit_Operation_Where_Add001]
      ,[R_Unit_Operation_Where_Add001]
      ,[U_Pharmacopeial_Material_001]
      ,[R_Pharmacopeial_Material_001]
      ,[U_SAP_JDE__Part_Number002]
      ,[R_SAP_JDE__Part_Number002]
      ,[U_Supplier_Name_Part_Number002]
      ,[R_Supplier_Name_Part_Number002]
      ,[U_Unit_Operation_Where_Add002]
      ,[R_Unit_Operation_Where_Add002]
      ,[U_Pharmacopeial_Material_002]
      ,[R_Pharmacopeial_Material_002]
      ,[U_Target_Difference_SU_versus]
      ,[R_Target_Difference_SU_versus]
      ,[U_Change_to_be_decided]
      ,[R_Change_to_be_decided]
      ,[U_Rationale___Explanation]
      ,[R_Rationale___Explanation]
      ,[U_Technical_Risk___Business_R]
      ,[R_Technical_Risk___Business_R]
      ,[U_Product___Process_Risk]
      ,[R_Product___Process_Risk]
      ,[C_PTP_Score] as [U_PTP_Score]
      ,[R_PTP_Score]
      ,[U_Required_Action]
      ,[R_Required_Action]
      ,[U_Comments___Actions]
      ,[R_Comments___Actions]
      ,[U_Send_to_Action_Plan_]
      ,[R_Send_to_Action_Plan_]
      ,[U_References]
      ,[R_References] FROM [StatureDev].[dbo].[X_PTP - Raw Mat_glbl_pub_new]
union
SELECT [ROW_ID]
      ,[VERSION_ID]
      ,[REVISION_ID]
      ,[FULL_VERSION_NAME]
      ,[BO_TYPE_NAME]
      ,[BO_TYPE_VERSION_NUMBER]
      ,[U_Revision_Name]
      ,[R_Revision_Name]
      ,[U_Raw_Material]
      ,[R_Raw_Material]
      ,[U_An_Excipient_]
      ,[R_An_Excipient_]
      ,[U_Criticality_Designation_if_]
      ,[R_Criticality_Designation_if_]
      ,[U_SAP_JDE__Part_Number001]
      ,[R_SAP_JDE__Part_Number001]
      ,[U_Supplier_Name_Part_Number001]
      ,[R_Supplier_Name_Part_Number001]
      ,[U_Unit_Operation_Where_Add001]
      ,[R_Unit_Operation_Where_Add001]
      ,[U_Pharmacopeial_Material_001]
      ,[R_Pharmacopeial_Material_001]
      ,[U_SAP_JDE__Part_Number002]
      ,[R_SAP_JDE__Part_Number002]
      ,[U_Supplier_Name_Part_Number002]
      ,[R_Supplier_Name_Part_Number002]
      ,[U_Unit_Operation_Where_Add002]
      ,[R_Unit_Operation_Where_Add002]
      ,[U_Pharmacopeial_Material_002]
      ,[R_Pharmacopeial_Material_002]
      ,[U_Target_Difference_SU_versus]
      ,[R_Target_Difference_SU_versus]
      ,[U_Change_to_be_decided]
      ,[R_Change_to_be_decided]
      ,[U_Rationale___Explanation]
      ,[R_Rationale___Explanation]
      ,[U_Technical_Risk___Business_R]
      ,[R_Technical_Risk___Business_R]
      ,[U_Product___Process_Risk]
      ,[R_Product___Process_Risk]
      ,[C_PTP_Score] as [U_PTP_Score]
      ,[R_PTP_Score]
      ,[U_Required_Action]
      ,[R_Required_Action]
      ,[U_Comments___Actions]
      ,[R_Comments___Actions]
      ,[U_Send_to_Action_Plan_]
      ,[R_Send_to_Action_Plan_]
      ,[U_References]
      ,[R_References] FROM [StatureDev].[dbo].[X_PTP - Raw Mat_glbl_rel_new]
union
SELECT [ROW_ID]
      ,[VERSION_ID]
      ,[REVISION_ID]
      ,[FULL_VERSION_NAME]
      ,[BO_TYPE_NAME]
      ,[BO_TYPE_VERSION_NUMBER]
      ,[U_Revision_Name]
      ,[R_Revision_Name]
      ,[U_Raw_Material]
      ,[R_Raw_Material]
      ,[U_An_Excipient_]
      ,[R_An_Excipient_]
      ,[U_Criticality_Designation_if_]
      ,[R_Criticality_Designation_if_]
      ,[U_SAP_JDE__Part_Number] as [U_SAP_JDE__Part_Number001]
      ,[R_SAP_JDE__Part_Number] as [R_SAP_JDE__Part_Number001]
      ,[U_Supplier_Name_Part_Number001]
      ,[R_Supplier_Name_Part_Number001]
      ,[U_Unit_Operation_Where_Add001]
      ,[R_Unit_Operation_Where_Add001]
      ,[U_Pharmacopeial_Material_001]
      ,[R_Pharmacopeial_Material_001]
      ,[U_SAP_JDE__Part_Number] as [U_SAP_JDE__Part_Number002]
      ,[R_SAP_JDE__Part_Number] as [R_SAP_JDE__Part_Number002]
      ,[U_Supplier_Name_Part_Number002]
      ,[R_Supplier_Name_Part_Number002]
      ,[U_Unit_Operation_Where_Add002]
      ,[R_Unit_Operation_Where_Add002]
      ,[U_Pharmacopeial_Material_002]
      ,[R_Pharmacopeial_Material_002]
      ,[U_Target_Difference_SU_versus]
      ,[R_Target_Difference_SU_versus]
      ,[U_Change_to_be_decided]
      ,[R_Change_to_be_decided]
      ,[U_Rationale___Explanation]
      ,[R_Rationale___Explanation]
      ,[U_Technical_Risk___Business_R]
      ,[R_Technical_Risk___Business_R]
      ,[U_Product___Process_Risk]
      ,[R_Product___Process_Risk]
      ,[C_PTP_Score] as [U_PTP_Score]
      ,[R_PTP_Score]
      ,[U_Required_Action]
      ,[R_Required_Action]
      ,[U_Comments___Actions]
      ,[R_Comments___Actions]
      ,[U_Send_to_Action_Plan_]
      ,[R_Send_to_Action_Plan_]
      ,[U_References]
      ,[R_References] FROM [StatureDev].[dbo].[X_PTP - Raw Mat_Site_pub_new]
union
SELECT [ROW_ID]
      ,[VERSION_ID]
      ,[REVISION_ID]
      ,[FULL_VERSION_NAME]
      ,[BO_TYPE_NAME]
      ,[BO_TYPE_VERSION_NUMBER]
      ,[U_Revision_Name]
      ,[R_Revision_Name]
      ,[U_Raw_Material]
      ,[R_Raw_Material]
      ,[U_An_Excipient_]
      ,[R_An_Excipient_]
      ,[U_Criticality_Designation_if_]
      ,[R_Criticality_Designation_if_]
      ,[U_SAP_JDE__Part_Number] as [U_SAP_JDE__Part_Number001]
      ,[R_SAP_JDE__Part_Number] as [R_SAP_JDE__Part_Number001]
      ,[U_Supplier_Name_Part_Number001]
      ,[R_Supplier_Name_Part_Number001]
      ,[U_Unit_Operation_Where_Add001]
      ,[R_Unit_Operation_Where_Add001]
      ,[U_Pharmacopeial_Material_001]
      ,[R_Pharmacopeial_Material_001]
      ,[U_SAP_JDE__Part_Number] as [U_SAP_JDE__Part_Number002]
      ,[R_SAP_JDE__Part_Number] as [R_SAP_JDE__Part_Number002]
      ,[U_Supplier_Name_Part_Number002]
      ,[R_Supplier_Name_Part_Number002]
      ,[U_Unit_Operation_Where_Add002]
      ,[R_Unit_Operation_Where_Add002]
      ,[U_Pharmacopeial_Material_002]
      ,[R_Pharmacopeial_Material_002]
      ,[U_Target_Difference_SU_versus]
      ,[R_Target_Difference_SU_versus]
      ,[U_Change_to_be_decided]
      ,[R_Change_to_be_decided]
      ,[U_Rationale___Explanation]
      ,[R_Rationale___Explanation]
      ,[U_Technical_Risk___Business_R]
      ,[R_Technical_Risk___Business_R]
      ,[U_Product___Process_Risk]
      ,[R_Product___Process_Risk]
      ,[C_PTP_Score] as [U_PTP_Score]
      ,[R_PTP_Score]
      ,[U_Required_Action]
      ,[R_Required_Action]
      ,[U_Comments___Actions]
      ,[R_Comments___Actions]
      ,[U_Send_to_Action_Plan_]
      ,[R_Send_to_Action_Plan_]
      ,[U_References]
      ,[R_References] FROM [StatureDev].[dbo].[X_PTP-Raw Mat_Site_draft_new]
GO


