USE [StatureDev]
GO

/****** Object:  View [dbo].[X_PTP-IPC]    Script Date: 9/5/2025 2:48:00 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO








CREATE   view [dbo].[X_PTP-IPC]
AS 
SELECT [ROW_ID]
      ,[VERSION_ID]
      ,[REVISION_ID]
      ,[FULL_VERSION_NAME]
      ,[BO_TYPE_NAME]
      ,[BO_TYPE_VERSION_NUMBER]
      ,[U_Revision_Name]
      ,[R_Revision_Name]
      ,[U_Process_Attribute]
      ,[R_Process_Attribute]
      ,[U_Attribute_Type]
      ,[R_Attribute_Type]
      ,[U_Applicability]
      ,[R_Applicability]
      ,[U_Sub_Step001]
      ,[R_Sub_Step001]
      ,[U_Test_Type001]
      ,[R_Test_Type001]
      ,[U_Limit_Type001]
      ,[R_Limit_Type001]
      ,[U_Assay001]
      ,[R_Assay001]
      ,[U_Assay_Readout001]
      ,[R_Assay_Readout001]
      ,[U_Site_Limits001]
      ,[R_Site_Limits001]
      ,[U_Site_Specific_Comments001]
      ,[R_Site_Specific_Comments001]
      ,[U_References001]
      ,[R_References001]
      ,[U_Sub_Step002]
      ,[R_Sub_Step002]
      ,[U_Test_Type002]
      ,[R_Test_Type002]
      ,[U_Limit_Type002]
      ,[R_Limit_Type002]
      ,[U_Assay002]
      ,[R_Assay002]
      ,[U_Assay_Readout002]
      ,[R_Assay_Readout002]
      ,[U_Site_Limits002]
      ,[R_Site_Limits002]
      ,[U_Site_Specific_Comments002]
      ,[R_Site_Specific_Comments002]
      ,[U_References002]
      ,[R_References002]
      ,[U_Difference_SU_versus_RU]
      ,[R_Difference_SU_versus_RU]
      ,[U_Change_to_be_decided]
      ,[R_Change_to_be_decided]
      ,[U_Rationale___Explanation]
      ,[R_Rationale___Explanation]
      ,[U_Technical_Risk___Business_R]
      ,[R_Technical_Risk___Business_R]
      ,[U_Product___Process_Risk]
      ,[R_Product___Process_Risk]
      ,[C_PTP_Score] as [U_PTP_Score] 
      ,[R_PTP_Score]
      ,[U_Required_Action]
      ,[R_Required_Action]
      ,[U_Comments___Actions]
      ,[R_Comments___Actions]
      ,[U_Send_to_Action_Plan_]
      ,[R_Send_to_Action_Plan_]
      ,[U_References003]
      ,[R_References003] FROM [StatureDev].[dbo].[X_PTP-IPC_global_pub_new]
union
SELECT [ROW_ID]
      ,[VERSION_ID]
      ,[REVISION_ID]
      ,[FULL_VERSION_NAME]
      ,[BO_TYPE_NAME]
      ,[BO_TYPE_VERSION_NUMBER]
      ,[U_Revision_Name]
      ,[R_Revision_Name]
      ,[U_Process_Attribute]
      ,[R_Process_Attribute]
      ,[U_Attribute_Type]
      ,[R_Attribute_Type]
      ,[U_Applicability]
      ,[R_Applicability]
      ,[U_Sub_Step001]
      ,[R_Sub_Step001]
      ,[U_Test_Type001]
      ,[R_Test_Type001]
      ,[U_Limit_Type001]
      ,[R_Limit_Type001]
      ,[U_Assay001]
      ,[R_Assay001]
      ,[U_Assay_Readout001]
      ,[R_Assay_Readout001]
      ,[U_Site_Limits001]
      ,[R_Site_Limits001]
      ,[U_Site_Specific_Comments001]
      ,[R_Site_Specific_Comments001]
      ,[U_References001]
      ,[R_References001]
      ,[U_Sub_Step002]
      ,[R_Sub_Step002]
      ,[U_Test_Type002]
      ,[R_Test_Type002]
      ,[U_Limit_Type002]
      ,[R_Limit_Type002]
      ,[U_Assay002]
      ,[R_Assay002]
      ,[U_Assay_Readout002]
      ,[R_Assay_Readout002]
      ,[U_Site_Limits002]
      ,[R_Site_Limits002]
      ,[U_Site_Specific_Comments002]
      ,[R_Site_Specific_Comments002]
      ,[U_References002]
      ,[R_References002]
      ,[U_Difference_SU_versus_RU]
      ,[R_Difference_SU_versus_RU]
      ,[U_Change_to_be_decided]
      ,[R_Change_to_be_decided]
      ,[U_Rationale___Explanation]
      ,[R_Rationale___Explanation]
      ,[U_Technical_Risk___Business_R]
      ,[R_Technical_Risk___Business_R]
      ,[U_Product___Process_Risk]
      ,[R_Product___Process_Risk]
      ,[C_PTP_Score] as [U_PTP_Score] 
      ,[R_PTP_Score]
      ,[U_Required_Action]
      ,[R_Required_Action]
      ,[U_Comments___Actions]
      ,[R_Comments___Actions]
      ,[U_Send_to_Action_Plan_]
      ,[R_Send_to_Action_Plan_]
      ,[U_References003]
      ,[R_References003] FROM [StatureDev].[dbo].[X_PTP-IPC_global_rel_new]
union
SELECT [ROW_ID]
      ,[VERSION_ID]
      ,[REVISION_ID]
      ,[FULL_VERSION_NAME]
      ,[BO_TYPE_NAME]
      ,[BO_TYPE_VERSION_NUMBER]
      ,[U_Revision_Name]
      ,[R_Revision_Name]
      ,[U_Process_Attribute]
      ,[R_Process_Attribute]
      ,[U_Attribute_Type]
      ,[R_Attribute_Type]
      ,[U_Applicability]
      ,[R_Applicability]
      ,[U_Sub_Step001]
      ,[R_Sub_Step001]
      ,[U_Test_Type001]
      ,[R_Test_Type001]
      ,[U_Limit_Type001]
      ,[R_Limit_Type001]
      ,[U_Assay001]
      ,[R_Assay001]
      ,[U_Assay_Readout001]
      ,[R_Assay_Readout001]
      ,[U_Site_Limits001]
      ,[R_Site_Limits001]
      ,[U_Site_Specific_Comments001]
      ,[R_Site_Specific_Comments001]
      ,[U_References001]
      ,[R_References001]
      ,[U_Sub_Step002]
      ,[R_Sub_Step002]
      ,[U_Test_Type002]
      ,[R_Test_Type002]
      ,[U_Limit_Type002]
      ,[R_Limit_Type002]
      ,[U_Assay002]
      ,[R_Assay002]
      ,[U_Assay_Readout002]
      ,[R_Assay_Readout002]
      ,[U_Site_Limits002]
      ,[R_Site_Limits002]
      ,[U_Site_Specific_Comments002]
      ,[R_Site_Specific_Comments002]
      ,[U_References002]
      ,[R_References002]
      ,[U_Difference_SU_versus_RU]
      ,[R_Difference_SU_versus_RU]
      ,[U_Change_to_be_decided]
      ,[R_Change_to_be_decided]
      ,[U_Rationale___Explanation]
      ,[R_Rationale___Explanation]
      ,[U_Technical_Risk___Business_R]
      ,[R_Technical_Risk___Business_R]
      ,[U_Product___Process_Risk]
      ,[R_Product___Process_Risk]
      ,[C_PTP_Score] as [U_PTP_Score] 
      ,[R_PTP_Score]
      ,[U_Required_Action]
      ,[R_Required_Action]
      ,[U_Comments___Actions]
      ,[R_Comments___Actions]
      ,[U_Send_to_Action_Plan_]
      ,[R_Send_to_Action_Plan_]
      ,[U_References003]
      ,[R_References003] FROM [StatureDev].[dbo].[X_PTP - IPC_Sit_publish_new]
union
SELECT [ROW_ID]
      ,[VERSION_ID]
      ,[REVISION_ID]
      ,[FULL_VERSION_NAME]
      ,[BO_TYPE_NAME]
      ,[BO_TYPE_VERSION_NUMBER]
      ,[U_Revision_Name]
      ,[R_Revision_Name]
      ,[U_Process_Attribute]
      ,[R_Process_Attribute]
      ,[U_Attribute_Type]
      ,[R_Attribute_Type]
      ,[U_Applicability]
      ,[R_Applicability]
      ,[U_Sub_Step001]
      ,[R_Sub_Step001]
      ,[U_Test_Type001]
      ,[R_Test_Type001]
      ,[U_Limit_Type001]
      ,[R_Limit_Type001]
      ,[U_Assay001]
      ,[R_Assay001]
      ,[U_Assay_Readout001]
      ,[R_Assay_Readout001]
      ,[U_Site_Limits001]
      ,[R_Site_Limits001]
      ,[U_Site_Specific_Comments001]
      ,[R_Site_Specific_Comments001]
      ,[U_References001]
      ,[R_References001]
      ,[U_Sub_Step002]
      ,[R_Sub_Step002]
      ,[U_Test_Type002]
      ,[R_Test_Type002]
      ,[U_Limit_Type002]
      ,[R_Limit_Type002]
      ,[U_Assay002]
      ,[R_Assay002]
      ,[U_Assay_Readout002]
      ,[R_Assay_Readout002]
      ,[U_Site_Limits002]
      ,[R_Site_Limits002]
      ,[U_Site_Specific_Comments002]
      ,[R_Site_Specific_Comments002]
      ,[U_References002]
      ,[R_References002]
      ,[U_Difference_SU_versus_RU]
      ,[R_Difference_SU_versus_RU]
      ,[U_Change_to_be_decided]
      ,[R_Change_to_be_decided]
      ,[U_Rationale___Explanation]
      ,[R_Rationale___Explanation]
      ,[U_Technical_Risk___Business_R]
      ,[R_Technical_Risk___Business_R]
      ,[U_Product___Process_Risk]
      ,[R_Product___Process_Risk]
      ,[C_PTP_Score] as [U_PTP_Score] 
      ,[R_PTP_Score]
      ,[U_Required_Action]
      ,[R_Required_Action]
      ,[U_Comments___Actions]
      ,[R_Comments___Actions]
      ,[U_Send_to_Action_Plan_]
      ,[R_Send_to_Action_Plan_]
      ,[U_References003]
      ,[R_References003] FROM [StatureDev].[dbo].[X_PTP-IPC_Site_draft_new]
GO


