USE [StatureDev]
GO

/****** Object:  View [dbo].[X_PTP-Manufacturing Components]    Script Date: 9/5/2025 2:48:39 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO








CREATE   view [dbo].[X_PTP-Manufacturing Components]
AS 
SELECT [ROW_ID]
      ,[VERSION_ID]
      ,[REVISION_ID]
      ,[FULL_VERSION_NAME]
      ,[BO_TYPE_NAME]
      ,[BO_TYPE_VERSION_NUMBER]
      ,[U_Revision_Name]
      ,[R_Revision_Name]
      ,[U_Manufacturing_Component]
      ,[R_Manufacturing_Component]
      ,[U_Criticality_Designation_if_]
      ,[R_Criticality_Designation_if_]
      ,[U_SAP_JDE_Part_Number001]
      ,[R_SAP_JDE_Part_Number001]
      ,[U_Supplier_Name_Part_Number001]
      ,[R_Supplier_Name_Part_Number001]
      ,[U_Unit_Operation_Where_Used001]
      ,[R_Unit_Operation_Where_Used001]
      ,[U_SAP_JDE_Part_Number002]
      ,[R_SAP_JDE_Part_Number002]
      ,[U_Supplier_Name_Part_Number002]
      ,[R_Supplier_Name_Part_Number002]
      ,[U_Unit_Operation_Where_Used002]
      ,[R_Unit_Operation_Where_Used002]
      ,[U_Target_Difference_SU_versus]
      ,[R_Target_Difference_SU_versus]
      ,[U_Change_to_be_decided]
      ,[R_Change_to_be_decided]
      ,[U_Rationale___Explanation]
      ,[R_Rationale___Explanation]
      ,[U_Technical_Risk___Business_R]
      ,[R_Technical_Risk___Business_R]
      ,[U_Product___Process_Risk]
      ,[R_Product___Process_Risk]
      ,[C_PTP_Score] as [U_PTP_Score]
      ,[R_PTP_Score]
      ,[U_Required_Action]
      ,[R_Required_Action]
      ,[U_Comments___Actions]
      ,[R_Comments___Actions]
      ,[U_Send_to_Action_Plan_]
      ,[R_Send_to_Action_Plan_]
      ,[U_References]
      ,[R_References] FROM [StatureDev].[dbo].[X_PTP - Man Com_glbl_pub_new]
union
SELECT  [ROW_ID]
      ,[VERSION_ID]
      ,[REVISION_ID]
      ,[FULL_VERSION_NAME]
      ,[BO_TYPE_NAME]
      ,[BO_TYPE_VERSION_NUMBER]
      ,[U_Revision_Name]
      ,[R_Revision_Name]
      ,[U_Manufacturing_Component]
      ,[R_Manufacturing_Component]
      ,[U_Criticality_Designation_if_]
      ,[R_Criticality_Designation_if_]
      ,[U_SAP_JDE_Part_Number001]
      ,[R_SAP_JDE_Part_Number001]
      ,[U_Supplier_Name_Part_Number001]
      ,[R_Supplier_Name_Part_Number001]
      ,[U_Unit_Operation_Where_Used001]
      ,[R_Unit_Operation_Where_Used001]
      ,[U_SAP_JDE_Part_Number002]
      ,[R_SAP_JDE_Part_Number002]
      ,[U_Supplier_Name_Part_Number002]
      ,[R_Supplier_Name_Part_Number002]
      ,[U_Unit_Operation_Where_Used002]
      ,[R_Unit_Operation_Where_Used002]
      ,[U_Target_Difference_SU_versus]
      ,[R_Target_Difference_SU_versus]
      ,[U_Change_to_be_decided]
      ,[R_Change_to_be_decided]
      ,[U_Rationale___Explanation]
      ,[R_Rationale___Explanation]
      ,[U_Technical_Risk___Business_R]
      ,[R_Technical_Risk___Business_R]
      ,[U_Product___Process_Risk]
      ,[R_Product___Process_Risk]
      ,[C_PTP_Score] as [U_PTP_Score]
      ,[R_PTP_Score]
      ,[U_Required_Action]
      ,[R_Required_Action]
      ,[U_Comments___Actions]
      ,[R_Comments___Actions]
      ,[U_Send_to_Action_Plan_]
      ,[R_Send_to_Action_Plan_]
      ,[U_References]
      ,[R_References] FROM [StatureDev].[dbo].[X_PTP - Man Com_glbl_rel_new]
union
SELECT  [ROW_ID]
      ,[VERSION_ID]
      ,[REVISION_ID]
      ,[FULL_VERSION_NAME]
      ,[BO_TYPE_NAME]
      ,[BO_TYPE_VERSION_NUMBER]
      ,[U_Revision_Name]
      ,[R_Revision_Name]
      ,[U_Manufacturing_Component]
      ,[R_Manufacturing_Component]
      ,[U_Criticality_Designation_if_]
      ,[R_Criticality_Designation_if_]
      ,[U_SAP_JDE_Part_Number001]
      ,[R_SAP_JDE_Part_Number001]
      ,[U_Supplier_Name_Part_Number001]
      ,[R_Supplier_Name_Part_Number001]
      ,[U_Unit_Operation_Where_Used001]
      ,[R_Unit_Operation_Where_Used001]
      ,[U_SAP_JDE_Part_Number002]
      ,[R_SAP_JDE_Part_Number002]
      ,[U_Supplier_Name_Part_Number002]
      ,[R_Supplier_Name_Part_Number002]
      ,[U_Unit_Operation_Where_Used002]
      ,[R_Unit_Operation_Where_Used002]
      ,[U_Target_Difference_SU_versus]
      ,[R_Target_Difference_SU_versus]
      ,[U_Change_to_be_decided]
      ,[R_Change_to_be_decided]
      ,[U_Rationale___Explanation]
      ,[R_Rationale___Explanation]
      ,[U_Technical_Risk___Business_R]
      ,[R_Technical_Risk___Business_R]
      ,[U_Product___Process_Risk]
      ,[R_Product___Process_Risk]
      ,[C_PTP_Score] as [U_PTP_Score]
      ,[R_PTP_Score]
      ,[U_Required_Action]
      ,[R_Required_Action]
      ,[U_Comments___Actions]
      ,[R_Comments___Actions]
      ,[U_Send_to_Action_Plan_]
      ,[R_Send_to_Action_Plan_]
      ,[U_References]
      ,[R_References] FROM [StatureDev].[dbo].[X_PTP - Man Comp_site_pub_new]
union
SELECT  [ROW_ID]
      ,[VERSION_ID]
      ,[REVISION_ID]
      ,[FULL_VERSION_NAME]
      ,[BO_TYPE_NAME]
      ,[BO_TYPE_VERSION_NUMBER]
      ,[U_Revision_Name]
      ,[R_Revision_Name]
      ,[U_Manufacturing_Component]
      ,[R_Manufacturing_Component]
      ,[U_Criticality_Designation_if_]
      ,[R_Criticality_Designation_if_]
      ,[U_SAP_JDE_Part_Number001]
      ,[R_SAP_JDE_Part_Number001]
      ,[U_Supplier_Name_Part_Number001]
      ,[R_Supplier_Name_Part_Number001]
      ,[U_Unit_Operation_Where_Used001]
      ,[R_Unit_Operation_Where_Used001]
      ,[U_SAP_JDE_Part_Number002]
      ,[R_SAP_JDE_Part_Number002]
      ,[U_Supplier_Name_Part_Number002]
      ,[R_Supplier_Name_Part_Number002]
      ,[U_Unit_Operation_Where_Used002]
      ,[R_Unit_Operation_Where_Used002]
      ,[U_Target_Difference_SU_versus]
      ,[R_Target_Difference_SU_versus]
      ,[U_Change_to_be_decided]
      ,[R_Change_to_be_decided]
      ,[U_Rationale___Explanation]
      ,[R_Rationale___Explanation]
      ,[U_Technical_Risk___Business_R]
      ,[R_Technical_Risk___Business_R]
      ,[U_Product___Process_Risk]
      ,[R_Product___Process_Risk]
      ,[C_PTP_Score] as [U_PTP_Score]
      ,[R_PTP_Score]
      ,[U_Required_Action]
      ,[R_Required_Action]
      ,[U_Comments___Actions]
      ,[R_Comments___Actions]
      ,[U_Send_to_Action_Plan_]
      ,[R_Send_to_Action_Plan_]
      ,[U_References]
      ,[R_References] FROM [StatureDev].[dbo].[X_PTP - Man Comp_site_dft_new]
GO


