USE [StatureDev]
GO

/****** Object:  View [dbo].[X_PTP-UO]    Script Date: 9/5/2025 2:49:37 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO








CREATE   view [dbo].[X_PTP-UO]
AS 
SELECT [ROW_ID]
      ,[VERSION_ID]
      ,[REVISION_ID]
      ,[FULL_VERSION_NAME]
      ,[BO_TYPE_NAME]
      ,[BO_TYPE_VERSION_NUMBER]
      ,[U_Revision_Name]
      ,[R_Revision_Name]
      ,[U_Process_Stage]
      ,[R_Process_Stage]
      ,[U_Parameter___Equipment___Mat]
      ,[R_Parameter___Equipment___Mat]
      ,[U_PTP_Category]
      ,[R_PTP_Category]
      ,[U_Criticality_Designation_if_]
      ,[R_Criticality_Designation_if_]
      ,[U_PAR]
      ,[R_PAR]
      ,[U_Applicability]
      ,[R_Applicability]
      ,[U_Target_SU]
      ,[R_Target_SU]
      ,[C_Set_Point001] as [U_Set_Point001]
      ,[R_Set_Point001]
      ,[C_NOR_LL001] as [U_NOR_LL001]
      ,[R_NOR_LL001]
      ,[C_NOR_UL001] as [U_NOR_UL001]
      ,[R_NOR_UL001]
      ,[U_Licensed_Limit_Range_SU__op]
      ,[R_Licensed_Limit_Range_SU__op]
      ,[U_Licensed_Countries001]
      ,[R_Licensed_Countries001]
      ,[U_Target_RU]
      ,[R_Target_RU]
      ,[C_Set_Point002] as [U_Set_Point002]
      ,[R_Set_Point002]
      ,[C_NOR_LL002] as [U_NOR_LL002]
      ,[R_NOR_LL002]
      ,[C_NOR_UL002] as [U_NOR_UL002]
      ,[R_NOR_UL002]
      ,[U_Licensed_Limit_Range_RU__op]
      ,[R_Licensed_Limit_Range_RU__op]
      ,[U_Licensed_Countries002]
      ,[R_Licensed_Countries002]
      ,[U_Target_Difference_SU_versus]
      ,[R_Target_Difference_SU_versus]
      ,[U_Difference_to_Product_Licen]
      ,[R_Difference_to_Product_Licen]
      ,[U_Change_to_be_decided]
      ,[R_Change_to_be_decided]
      ,[U_Rationale___Explanation]
      ,[R_Rationale___Explanation]
      ,[U_Technical_Risk___Business_R]
      ,[R_Technical_Risk___Business_R]
      ,[U_Product___Process_Risk]
      ,[R_Product___Process_Risk]
      ,[C_PTP_Score] as [U_PTP_Score] 
      ,[R_PTP_Score]
      ,[U_Required_Action]
      ,[R_Required_Action]
      ,[U_Comments___Actions]
      ,[R_Comments___Actions]
      ,[U_Send_to_Action_Plan_]
      ,[R_Send_to_Action_Plan_]
      ,[U_References]
      ,[R_References] FROM [StatureDev].[dbo].[X_PTP - UO Set_glbl_pub_new]
union
SELECT [ROW_ID]
      ,[VERSION_ID]
      ,[REVISION_ID]
      ,[FULL_VERSION_NAME]
      ,[BO_TYPE_NAME]
      ,[BO_TYPE_VERSION_NUMBER]
      ,[U_Revision_Name]
      ,[R_Revision_Name]
      ,[U_Process_Stage]
      ,[R_Process_Stage]
      ,[U_Parameter___Equipment___Mat]
      ,[R_Parameter___Equipment___Mat]
      ,[U_PTP_Category]
      ,[R_PTP_Category]
      ,[U_Criticality_Designation_if_]
      ,[R_Criticality_Designation_if_]
      ,[U_PAR]
      ,[R_PAR]
      ,[U_Applicability]
      ,[R_Applicability]
      ,[U_Target_SU]
      ,[R_Target_SU]
      ,[C_Set_Point001] as [U_Set_Point001]
      ,[R_Set_Point001]
      ,[C_NOR_LL001] as [U_NOR_LL001]
      ,[R_NOR_LL001]
      ,[C_NOR_UL001] as [U_NOR_UL001]
      ,[R_NOR_UL001]
      ,[U_Licensed_Limit_Range_SU__op]
      ,[R_Licensed_Limit_Range_SU__op]
      ,[U_Licensed_Countries001]
      ,[R_Licensed_Countries001]
      ,[U_Target_RU]
      ,[R_Target_RU]
      ,[C_Set_Point002] as [U_Set_Point002]
      ,[R_Set_Point002]
      ,[C_NOR_LL002] as [U_NOR_LL002]
      ,[R_NOR_LL002]
      ,[C_NOR_UL002] as [U_NOR_UL002]
      ,[R_NOR_UL002]
      ,[U_Licensed_Limit_Range_RU__op]
      ,[R_Licensed_Limit_Range_RU__op]
      ,[U_Licensed_Countries002]
      ,[R_Licensed_Countries002]
      ,[U_Target_Difference_SU_versus]
      ,[R_Target_Difference_SU_versus]
      ,[U_Difference_to_Product_Licen]
      ,[R_Difference_to_Product_Licen]
      ,[U_Change_to_be_decided]
      ,[R_Change_to_be_decided]
      ,[U_Rationale___Explanation]
      ,[R_Rationale___Explanation]
      ,[U_Technical_Risk___Business_R]
      ,[R_Technical_Risk___Business_R]
      ,[U_Product___Process_Risk]
      ,[R_Product___Process_Risk]
      ,[C_PTP_Score] as [U_PTP_Score]
      ,[R_PTP_Score]
      ,[U_Required_Action]
      ,[R_Required_Action]
      ,[U_Comments___Actions]
      ,[R_Comments___Actions]
      ,[U_Send_to_Action_Plan_]
      ,[R_Send_to_Action_Plan_]
      ,[U_References]
      ,[R_References] FROM [StatureDev].[dbo].[X_PTP - UO Set_glbl_rel_new]
union
SELECT [ROW_ID]
      ,[VERSION_ID]
      ,[REVISION_ID]
      ,[FULL_VERSION_NAME]
      ,[BO_TYPE_NAME]
      ,[BO_TYPE_VERSION_NUMBER]
      ,[U_Revision_Name]
      ,[R_Revision_Name]
      ,[U_Sub_Step] as [U_Process_Stage]
      ,[R_Sub_Step] as [R_Process_Stage]
      ,[U_Parameter___Equipment___Mat]
      ,[R_Parameter___Equipment___Mat]
      ,[U_PTP_Category]
      ,[R_PTP_Category]
      ,[U_Criticality_Designation_if_]
      ,[R_Criticality_Designation_if_]
      ,[U_PAR]
      ,[R_PAR]
      ,[U_Applicability]
      ,[R_Applicability]
      ,[U_Target_SU]
      ,[R_Target_SU]
      ,[C_Set_Point001] as [U_Set_Point001]
      ,[R_Set_Point001]
      ,[C_NOR_LL001] as [U_NOR_LL001]
      ,[R_NOR_LL001]
      ,[C_NOR_UL001] as [U_NOR_UL001]
      ,[R_NOR_UL001]
      ,[U_Licensed_Limit_Range_SU__op]
      ,[R_Licensed_Limit_Range_SU__op]
      ,[U_Licensed_Countries001]
      ,[R_Licensed_Countries001]
      ,[U_Target_RU]
      ,[R_Target_RU]
      ,[C_Set_Point002] as [U_Set_Point002]
      ,[R_Set_Point002]
      ,[C_NOR_LL002] as [U_NOR_LL002]
      ,[R_NOR_LL002]
      ,[C_NOR_UL002] as [U_NOR_UL002]
      ,[R_NOR_UL002]
      ,[U_Licensed_Limit_Range_RU__op]
      ,[R_Licensed_Limit_Range_RU__op]
      ,[U_Licensed_Countries002]
      ,[R_Licensed_Countries002]
      ,[U_Target_Difference_SU_versus]
      ,[R_Target_Difference_SU_versus]
      ,[U_Difference_to_Product_Licen]
      ,[R_Difference_to_Product_Licen]
      ,[U_Change_to_be_decided]
      ,[R_Change_to_be_decided]
      ,[U_Rationale___Explanation]
      ,[R_Rationale___Explanation]
      ,[U_Technical_Risk___Business_R]
      ,[R_Technical_Risk___Business_R]
      ,[U_Product___Process_Risk]
      ,[R_Product___Process_Risk]
      ,[C_PTP_Score] as [U_PTP_Score]
      ,[R_PTP_Score]
      ,[U_Required_Action]
      ,[R_Required_Action]
      ,[U_Comments___Actions]
      ,[R_Comments___Actions]
      ,[U_Send_to_Action_Plan_]
      ,[R_Send_to_Action_Plan_]
      ,[U_References]
      ,[R_References] FROM [StatureDev].[dbo].[X_PTP - UO Set_site_pub_new]
union
SELECT [ROW_ID]
      ,[VERSION_ID]
      ,[REVISION_ID]
      ,[FULL_VERSION_NAME]
      ,[BO_TYPE_NAME]
      ,[BO_TYPE_VERSION_NUMBER]
      ,[U_Revision_Name]
      ,[R_Revision_Name]
      ,[U_Sub_Step] as [U_Process_Stage]
      ,[R_Sub_Step] as [R_Process_Stage]
      ,[U_Parameter___Equipment___Mat]
      ,[R_Parameter___Equipment___Mat]
      ,[U_PTP_Category]
      ,[R_PTP_Category]
      ,[U_Criticality_Designation_if_]
      ,[R_Criticality_Designation_if_]
      ,[U_PAR]
      ,[R_PAR]
      ,[U_Applicability]
      ,[R_Applicability]
      ,[U_Target_SU]
      ,[R_Target_SU]
      ,[C_Set_Point001] as [U_Set_Point001]
      ,[R_Set_Point001]
      ,[C_NOR_LL001] as [U_NOR_LL001]
      ,[R_NOR_LL001]
      ,[C_NOR_UL001] as [U_NOR_UL001]
      ,[R_NOR_UL001]
      ,[U_Licensed_Limit_Range_SU__op]
      ,[R_Licensed_Limit_Range_SU__op]
      ,[U_Licensed_Countries001]
      ,[R_Licensed_Countries001]
      ,[U_Target_RU]
      ,[R_Target_RU]
      ,[C_Set_Point002] as [U_Set_Point002]
      ,[R_Set_Point002]
      ,[C_NOR_LL002] as [U_NOR_LL002]
      ,[R_NOR_LL002]
      ,[C_NOR_UL002] as [U_NOR_UL002]
      ,[R_NOR_UL002]
      ,[U_Licensed_Limit_Range_RU__op]
      ,[R_Licensed_Limit_Range_RU__op]
      ,[U_Licensed_Countries002]
      ,[R_Licensed_Countries002]
      ,[U_Target_Difference_SU_versus]
      ,[R_Target_Difference_SU_versus]
      ,[U_Difference_to_Product_Licen]
      ,[R_Difference_to_Product_Licen]
      ,[U_Change_to_be_decided]
      ,[R_Change_to_be_decided]
      ,[U_Rationale___Explanation]
      ,[R_Rationale___Explanation]
      ,[U_Technical_Risk___Business_R]
      ,[R_Technical_Risk___Business_R]
      ,[U_Product___Process_Risk]
      ,[R_Product___Process_Risk]
      ,[C_PTP_Score] as [U_PTP_Score]
      ,[R_PTP_Score]
      ,[U_Required_Action]
      ,[R_Required_Action]
      ,[U_Comments___Actions]
      ,[R_Comments___Actions]
      ,[U_Send_to_Action_Plan_]
      ,[R_Send_to_Action_Plan_]
      ,[U_References]
      ,[R_References] FROM [StatureDev].[dbo].[X_PTP - UO Set_site_rel_new]
GO


